# Generated by Django 4.0.2 on 2022-02-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.TextField(primary_key='True', serialize=False)),
                ('name', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
