# Generated by Django 4.0.2 on 2022-04-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
