# Generated by Django 4.0.2 on 2022-03-22 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='First name must start with a capital letter and contain only letters.', regex='^[A-Z][-a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Last name must start with a capital letter and contain only letters.', regex='^[A-Z][-a-zA-Z]+$')]),
        ),
    ]
